import type { Metadata } from "next";
import "./globals.css";

import { Inter, Instrument_Serif } from "next/font/google";
import Navbar from "@/components/Navbar";
import FloatingSocials from "@/components/FloatingSocials";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-instrument",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${instrumentSerif.variable}`}>
        <main className="pt-36">
          <Navbar />
          {children}
          <FloatingSocials />
          <Footer />
        </main>
      </body>
    </html>
  );
}
